### ISSUE TITLE
Core code to-do list

### ISSUE THREAD

**Issue by sam-may** [AutoDQM/AutoDQM_ML#18]
Here is my current to-do list on improvements to be made/features to be added to the core code.

Legend:
:bangbang: highest priority
:exclamation: higher priority
:turtle: lower priority/solution is time-intensive

- [ ] 1. DataFetcher
	- [ ] :turtle: 1.1 Automatically scale properly when running over a huge number of histograms (avoid huge memory usage)
- [ ] 2. Algorithms/training
	- [ ] :bangbang: 2.1 Train only with good runs by default
	- [ ] :bangbang: 2.2 Implement flattening of 2d histograms for PCAs (merge Si's code)
	- [ ] 2.3 Autoencoders
		- [ ] :exclamation: 2.3.1 Make default behavior to train a single AutoEncoder per histogram
	- [ ] :exclamation: 2.4 Make algorithms and training configurable through json input (rather than just CLIs)
- [ ] 3. Assessment
	- [ ] :bangbang: 3.1 Make SSE histograms for good/bad runs in addition to train/test set
	- [ ] :exclamation: 3.2 Make SSE histograms both in per-events set format and per-algorithm format
	- [ ] :exclamation: 3.3 Plotting of 2d histograms
	- [ ] :exclamation: 3.4 Function for ROC curve plots
	- [ ] :exclamation: 3.5 Function to make summary table of AUC and tpr/fpr values
	- [ ] :turtle: 3.6 Switch from yahist to boost, mplhep
